name: contact_permission_ios
description: iOS implementation of the contact_permission plugin
version: 0.1.0+1


environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.1"

flutter:
  plugin:
    implements: contact_permission
    platforms:
      ios:
        pluginClass: ContactPermissionPlugin
        dartPluginClass: ContactPermissionIOS

dependencies:
  flutter:
    sdk: flutter
  contact_permission_platform_interface:
    path: ../contact_permission_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^4.0.0
